[tools]
# runtimes
node = '20'
python = '3.10.12'
rust = 'latest'
java = 'temurin-8'
go = 'latest'
# tools
neovim = 'latest'
github-cli = 'latest'
# commandline tools
bat = 'latest'
eza = 'latest'
aws-cli = 'latest'
fzf = 'latest'
