[tools]

# -- [[ Runtimes ]]
java = 'temurin-8'
scala = "latest"

# -- [[ Tools ]]
sbt = "latest"
atlas = "latest"
buf = "latest"
terraform = "latest"
localstack = "latest"
mirrord = "latest"
minikube = "latest"

# -- [[ CLI Tools ]]
mark = "latest"
