[tools]

# -- [[ Runtimes ]]
java = "zulu-jre-8.90.0.19"

# -- [[ Tools ]]
atlas = "latest"
buf = "latest"
terraform = "latest"
localstack = "latest"
mirrord = "latest"
minikube = "latest"

# -- [[ CLI Tools ]]
mark = "latest"
uv = "latest"

[tasks.repos]
description = 'Search and open organization repositories'
run = 'gh s --user=Secful | xargs -I {} open --url {}'

